[project]
name = "broflow"
version = "0.2.0"
description = "Run your workflow with lightweight library. This is how broflow flows."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]

[tool.setuptools.packages.find]
include = ["broflow*"]

[dependency-groups]
dev = [
    "ipykernel>=6.30.0",
    "pytest>=9.1.1",
    "ruff>=0.16.6",
]
